# Generated by Django 5.2.7 on 2025-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagehistory_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
